---
parser: '@typescript-eslint/parser'
parserOptions:
    project: './tsconfig.json'
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
        impliedStrict: true
plugins:
    - '@typescript-eslint'
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
    - prettier/@typescript-eslint
env:
    browser: true
    node: true
    es6: true
rules:
    # https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
    '@typescript-eslint/array-type':
        - error
        - generic
    '@typescript-eslint/explicit-function-return-type': off
    '@typescript-eslint/explicit-member-accessibility': off
    '@typescript-eslint/member-naming': error
    '@typescript-eslint/member-ordering': error
    '@typescript-eslint/no-explicit-any': off
    '@typescript-eslint/no-extraneous-class': off
    '@typescript-eslint/no-extra-parens': error
    '@typescript-eslint/no-misused-new': error
    '@typescript-eslint/no-parameter-properties': off
    '@typescript-eslint/no-this-alias': error
    '@typescript-eslint/no-type-alias': error
    '@typescript-eslint/no-unnecessary-qualifier': error
    '@typescript-eslint/no-unnecessary-type-assertion': error
    '@typescript-eslint/no-use-before-define': off
    '@typescript-eslint/no-useless-constructor': error
    '@typescript-eslint/prefer-for-of': error
    '@typescript-eslint/prefer-includes': error
    '@typescript-eslint/prefer-string-starts-ends-with': error
    '@typescript-eslint/restrict-plus-operands': error
    array-bracket-newline:
        - error
        - multiline: true
    array-bracket-spacing: error
    arrow-body-style:
        - error
        - as-needed
    arrow-parens:
        - error
        - as-needed
    arrow-spacing: error
    block-scoped-var: error
    block-spacing: error
    brace-style: error
    camelcase: error
    comma-dangle:
        - error
        - always-multiline
    comma-spacing: error
    comma-style: error
    computed-property-spacing: error
    consistent-this: error
    curly: error
    default-case: error
    dot-notation: error
    eqeqeq: error
    eol-last: error
    for-direction: error
    func-call-spacing: error
    func-name-matching: error
    func-names:
        - error
        - never
    func-style: error
    getter-return: error
    key-spacing: error
    keyword-spacing: error
    line-comment-position: error
    linebreak-style:
        - error
        - windows
    max-classes-per-file: error
    max-depth: error
    max-len:
        - error
        - ignoreComments: true
          ignoreTrailingComments: true
          ignoreStrings: true
          ignoreTemplateLiterals: true
    max-lines: error
    max-lines-per-function:
        - error
        - max: 60
    max-nested-callbacks:
        - error
        - max: 4
    max-params: error
    max-statements:
        - error
        - max: 25
    max-statements-per-line: error
    new-parens: error
    no-alert: error
    no-array-constructor: error
    no-bitwise: error
    no-buffer-constructor: error
    no-caller: error
    no-confusing-arrow: error
    no-console: 0
    no-continue: error
    no-duplicate-imports: error
    no-else-return: error
    no-empty-function: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-extra-parens: error
    no-implicit-coercion: error
    no-implicit-globals: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    no-label-var: error
    no-labels: error
    no-lone-blocks: error
    no-lonely-if: error
    no-loop-func: error
    no-magic-numbers:
        - error
        - ignoreArrayIndexes: true
          enforceConst: true
          ignore:
              - 0
              - 1
              - -1
    no-multi-assign: error
    no-multi-spaces: error
    no-multiple-empty-lines: error
    no-negated-condition: error
    no-nested-ternary: error
    no-new: error
    no-new-func: error
    no-new-object: error
    no-new-wrappers: error
    no-param-reassign: error
    no-proto: error
    no-restricted-properties: error
    no-return-assign: error
    no-return-await: error
    no-script-url: error
    no-self-compare: error
    no-sequences: error
    no-shadow: error
    no-shadow-restricted-names: error
    no-tabs: error
    no-template-curly-in-string: error
    no-throw-literal: error
    no-trailing-spaces: error
    no-undef-init: error
    no-underscore-dangle:
        - error
        - allow:
              - _id
              - __v
    no-unmodified-loop-condition: error
    no-unneeded-ternary: error
    no-unused-expressions: error
    no-use-before-define:
        - error
        - functions: false
          classes: false
    no-useless-call: error
    no-useless-catch: error
    no-useless-computed-key: error
    no-useless-concat: error
    no-useless-constructor: error
    no-useless-rename: error
    no-useless-return: error
    no-var: error
    no-void: error
    no-whitespace-before-property: error
    no-with: error
    nonblock-statement-body-position: error
    object-curly-newline:
        - error
        - multiline: true
    object-property-newline:
        - error
        - allowAllPropertiesOnSameLine: true
    object-shorthand: error
    one-var:
        - error
        - never
    one-var-declaration-per-line: error
    operator-assignment: error
    operator-linebreak: error
    padded-blocks:
        - error
        - never
    prefer-arrow-callback: error
    prefer-const: error
    prefer-destructuring: error
    prefer-numeric-literals: error
    prefer-object-spread: error
    prefer-promise-reject-errors: error
    prefer-rest-params: error
    prefer-spread: error
    prefer-template: error
    quote-props:
        - error
        - as-needed
    quotes:
        - error
        - single
    radix: error
    require-atomic-updates: error
    require-await: error
    require-unicode-regexp: error
    rest-spread-spacing: error
    semi:
        - error
        - never
    semi-spacing: error
    sort-imports: error
    space-before-blocks: error
    space-before-function-paren:
        - error
        - asyncArrow: always
          named: never
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment: error
    strict: error
    switch-colon-spacing: error
    symbol-description: error
    template-curly-spacing: error
    wrap-iife: error
    yield-star-spacing: error
    yoda:
        - error
        - never
